---
# tasks file for pathogen

- name: "Create directories for pathogen and plugins"
  file: path=/etc/vim/{{ item }} state=directory
  with_items: [autoload, bundle]

- name: "Install pathogen"
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: /etc/vim/autoload/

- name: "Infect .vimrc"
  lineinfile:
    line: "execute pathogen#infect()"
    dest: "/etc/vim/vimrc.local"

- name: "Install plugins"
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version | default('master') }}"
    dest: "/etc/vim/bundle/{{ item.name | default(item.repo.split('/')[-1][:-4]) }}"
    depth: 1
  with_items: "{{ pathogen_plugins }}"
